<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\");\r\n    	 ",12,173);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",189,204);
$z[2]=Array("title","",220,234);
$z[3]=Array("pubdate","",297,343);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",375,389);
$z[5]=Array("scores","",421,436);
$z[6]=Array("description","",482,502);

?>