<section class="recommend">  
                        <header class="header">  
                            <h2><a href="[field:arcurl/]">[field:title/]</a></h2>  
                            <a href="[field:arcurl/]" class="more" title="更多...">more</a>  
                        </header>  
                        <div class="content">  
                            [field:body/]  
                        </div>  
                    </section>