<?php  exit();
/*
Page: /ZGHYGQXH/
Error: Unknown column 'id' in 'where clause' <br />Error sql: <font color='red'>select body from dede_addonarticle where id=2</font>
Time2017-10-21 15:42:25
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'orderby=desc' at line 1 <br />Error sql: <font color='red'>select body from dede_addonarticle where typeid=2 orderby=desc</font>
Time2017-10-21 15:45:56
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where typeid=2 orderby=desc' at line 1 <br />Error sql: <font color='red'>select body from dede_addonarticle order by aid desc where typeid=2 orderby=desc</font>
Time2017-10-21 15:47:18
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where typeid=2' at line 1 <br />Error sql: <font color='red'>select body from dede_addonarticle order by aid desc where typeid=2</font>
Time2017-10-21 15:47:28
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where typeid=2' at line 1 <br />Error sql: <font color='red'>select body from dede_addonarticle order by aid desc where typeid=2</font>
Time2017-10-21 15:48:11
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '3 FROM `dede_addonarticle` where typeid = 2 ORDER BY aid DESC' at line 1 <br />Error sql: <font color='red'>SELECT body TOP 3 FROM `dede_addonarticle` where typeid = 2 ORDER BY aid DESC</font>
Time2017-10-22 17:38:31
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '3 where typeid = 2 ORDER BY aid DESC' at line 1 <br />Error sql: <font color='red'>SELECT body FROM `dede_addonarticle` 3 where typeid = 2 ORDER BY aid DESC</font>
Time2017-10-22 17:39:14
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/index.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '3 where typeid = 2 ORDER BY aid DESC' at line 1 <br />Error sql: <font color='red'>SELECT body FROM `dede_addonarticle` 3 where typeid = 2 ORDER BY aid DESC</font>
Time2017-10-22 17:39:15
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '><a) And  arc.arcrank > -1     ORDER BY arc.id desc  LIMIT 0,3' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
        
         WHERE  arc.typeid IN (2><a) And  arc.arcrank > -1     ORDER BY arc.id desc  LIMIT 0,3 </font>
Time2017-10-22 19:08:41
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'esc  LIMIT 0,8' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
        
         WHERE  arc.typeid IN (3) And  arc.arcrank > -1    ORDER BY arc.sortrank esc  LIMIT 0,8 </font>
Time2017-10-22 20:43:53
*/
?>
<?php  exit();
/*
Page: /ZGHYGQXH/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'dsc  LIMIT 0,8' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
        
         WHERE  arc.typeid IN (3) And  arc.arcrank > -1    ORDER BY arc.sortrank dsc  LIMIT 0,8 </font>
Time2017-10-22 20:44:01
*/
?>
